### ISSUE TITLE
Line Clipping - Liang-Barsky

### ISSUE THREAD

**Issue by danielschroder** [quenio/INE5420#29]
We must implement the Liang-Barsky clipping algorithm.

**Comment by quenio** [comment]
Algorithm:
- Calculate the parameters `p` and `q` based on points `a` and `b` of Line, starting from `a`.
- Determine zeta-one and zeta-two based on the parameters `p` and `q`.
- If zeta-one > zeta-two, then Line is invisible (fully outside the Window), and we stop here.
- If zeta-one = 0, then there is no intersection point with the Window bounds from `a`, we continue to use `a` in Line.
- Otherwise, use zeta-one as the parameter on the line's parametric equation to find the intersection point from `a`. We replace `a` with the intersection point in Line.
- If zeta-two = 1, then there is no intersection point with the Window bounds from `b`, we continue to use `b` in Line.
- Otherwise, use zeta-two as the parameter on the line's parametric equation to find intersection point from `b`. We replace `b` with the intersection point in Line.
